import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    id: {
        "app.title": "Al Quran",
        "menu.asmaulHusna": "Asmaul Husna",
        "menu.dailyPrayers": "Doa Harian",
        "menu.dzikir": "Dzikir Pagi & Petang",
        "menu.doaKhatam": "Doa Khatam",
        "menu.profile": "Profil Saya",
        "menu.others": "Menu Lainnya",
        "menu.doaSholat": "Doa Sholat",
        "surah.verseView": "Tampilan Ayat",
        "surah.pageView": "Tampilan Halaman",
        "surah.selectScript": "Pilih Tulisan",
        "surah.plain": "Tanpa Tajwid",
        "surah.tajweed": "Dengan Tajwid",
        "surah.verse": "Ayat",
        "surah.loading": "Memuat...",
        "surah.shareTitle": "Bagikan Ayat",
        "surah.cancel": "Batal",
        "surah.shareImage": "Bagikan Gambar",
        "surah.end": "Akhir Surah",
        "surah.juz": "Juz",
        "surah.page": "Halaman",
        "surah.prev": "Sblm",
        "surah.next": "Lnjt",
        "home.lastRead": "Terakhir Dibaca",
        "home.dailyInspiration": "Inspirasi Harian",
        "home.searchPlaceholder": "Cari Surah...",
        "home.all": "Semua",
        "home.bookmarks": "Penanda",
        "home.verses": "Ayat",
        "tasbih.title": "Tasbih Digital",
        "tasbih.tap": "Tap",
        "tasbih.reset": "Reset",
        "tasbih.target": "Target",
        "tasbih.noTarget": "Tanpa Target",
        "tasbih.history": "Riwayat Dzikir",
        "tasbih.saveInfo": "Cara Menyimpan: Setiap kali Anda menekan tombol Reset, hitungan terakhir akan otomatis tersimpan.",
        "tasbih.noHistory": "Belum ada riwayat.",
        "tasbih.clearAll": "Hapus Semua",
        "tasbih.close": "Tutup",
        "tasbih.targetReached": "Target Tercapai!",
        "tasbih.reachedMsg": "Anda telah mencapai {count} hitungan.",
        "tasbih.continue": "Lanjut",
        "prayer.title": "Jadwal Sholat",
        "prayer.next": "Sholat Berikutnya",
        "prayer.enableLoc": "Aktifkan Lokasi",
        "prayer.refreshLoc": "Refresh Lokasi",
        "prayer.locating": "Mencari Lokasi...",
        "prayer.unknown": "Lokasi Tidak Diketahui",
        "prayer.fajr": "Subuh",
        "prayer.sunrise": "Terbit",
        "prayer.dhuhr": "Dzuhur",
        "prayer.asr": "Ashar",
        "prayer.maghrib": "Maghrib",
        "prayer.isha": "Isya",
        "prayer.testAdzan": "Tes Adzan",
        "prayer.testFajr": "Tes Subuh",
        "prayer.simulation": "Simulasi",
        "prayer.stop": "Stop Adzan",
        "qibla.title": "Arah Kiblat",
        "qibla.findingLoc": "Mencari GPS...",
        "qibla.findingCity": "Mencari nama kota...",
        "qibla.calibrate": "Kalibrasi Kompas",
        "qibla.calibrateInfo": "Gerakkan HP Anda membentuk angka 8 di udara untuk meningkatkan akurasi kompas.",
        "qibla.done": "Selesai",
        "asmaulHusna.subtitle": "99 Nama Allah yang Indah",
        "asmaulHusna.search": "Cari nama...",
        "dailyPrayers.subtitle": "Kumpulan Doa Sehari-hari",
        "dailyPrayers.search": "Cari doa...",
        "dailyPrayers.listen": "Dengarkan",
        "dailyPrayers.stop": "Stop",
        "dailyPrayers.pause": "Pause",
        "dailyPrayers.resume": "Lanjut",
        "dailyPrayers.audioUnavailable": "Audio tidak tersedia untuk doa ini.",
        "dzikir.subtitle": "Dzikir Pagi & Petang",
        "dzikir.search": "Cari dzikir...",
        "doaKhatam.subtitle": "Doa Khatam Al-Qur'an",
        "doaKhatam.search": "Cari doa...",
        "doaSholat.subtitle": "Bacaan Lengkap Sholat & Niat",
        "doaSholat.search": "Cari bacaan atau niat...",
        "doaSholat.category.bacaan": "Bacaan Sholat",
        "doaSholat.category.niatWajib": "Sholat Wajib",
        "doaSholat.category.niatSunnah": "Sholat Sunnah",
        "doaSholat.category.sholatJenazah": "Sholat Jenazah",
        "profile.title": "Profil Saya",
        "profile.savedBookmarks": "Penanda Tersimpan",
        "profile.noBookmarks": "Belum ada penanda.",
        "profile.surahs": "Surah",
        "profile.verses": "Ayat",
        "profile.signOut": "Keluar",
        "settings.title": "Pengaturan",
        "settings.arabicFontSize": "Ukuran Font Arab",
        "settings.arabicFontFamily": "Gaya Font Arab",
        "settings.fontStyleAmiri": "Amiri (Utsmani)",
        "settings.fontStyleIndopak": "Indopak",
        "settings.fontStyleLateef": "Lateef (Bold)",
        "mutabah.title": "Mutaba'ah Yaumiyah",
        "mutabah.subtitle": "Catatan Amal Harian",
        "mutabah.progress": "Progres Hari Ini",
        "mutabah.category.fardhu": "Sholat Fardhu",
        "mutabah.category.sunnah": "Sholat Sunnah",
        "mutabah.category.quran": "Al-Quran",
        "mutabah.category.others": "Lainnya",
        "ibadah.subuh": "Subuh",
        "ibadah.dhuhur": "Dzuhur",
        "ibadah.ashar": "Ashar",
        "ibadah.maghrib": "Maghrib",
        "ibadah.isya": "Isya",
        "ibadah.tahajjud": "Tahajjud",
        "ibadah.duha": "Duha",
        "ibadah.rawatib": "Rawatib",
        "ibadah.tilawah": "Tilawah",
        "ibadah.hafalan": "Hafalan",
        "ibadah.dzikirPagi": "Dzikir Pagi",
        "ibadah.dzikirPetang": "Dzikir Petang",
        "ibadah.sedekah": "Sedekah",
        "auth.welcomeBack": "Selamat Datang Kembali",
        "auth.signInSubtitle": "Masuk untuk menyinkronkan penanda Anda",
        "auth.email": "Email",
        "auth.password": "Kata Sandi",
        "auth.signIn": "Masuk",
        "auth.noAccount": "Belum punya akun?",
        "auth.signUp": "Daftar",
        "auth.createAccount": "Buat Akun",
        "auth.joinUs": "Bergabunglah untuk menyimpan progres Anda",
        "auth.haveAccount": "Sudah punya akun?",
        "auth.signupSuccess": "Pendaftaran berhasil! Cek email Anda.",
        "common.loading": "Memuat...",
        "common.error": "Terjadi kesalahan",
        "search.title": "Pencarian Global",
        "search.placeholder": "Cari kata kunci...",
        "search.noResults": "Tidak ada hasil ditemukan untuk '{query}'",
        "search.searching": "Mencari...",
        "search.resultsCount": "{count} hasil ditemukan",
        "bookmarks.title": "Bookmark Terpilih",
        "bookmarks.tags": "Tag Saya",
        "bookmarks.addTag": "Tambah Tag",
        "bookmarks.manageTags": "Kelola Tag",
        "bookmarks.filterAll": "Semua",
        "bookmarks.tagHafalan": "Hafalan",
        "bookmarks.tagFavorit": "Favorit",
        "bookmarks.tagPenting": "Penting",
        "bookmarks.noTags": "Belum ada tag",
        "search.backToSearch": "Kembali ke Pencarian",
        "menu.prophetStories": "Kisah Nabi",
        "prophetStories.subtitle": "Kisah 25 Nabi dalam Al-Quran",
        "prophetStories.search": "Cari nama nabi..."
    },
    en: {
        "app.title": "Al Quran",
        "menu.asmaulHusna": "Asmaul Husna",
        "menu.dailyPrayers": "Daily Prayers",
        "menu.dzikir": "Morning & Evening Dhikr",
        "menu.doaKhatam": "Khatam Prayer",
        "menu.profile": "My Profile",
        "menu.others": "Other Menu",
        "menu.doaSholat": "Prayer for Salah",
        "surah.verseView": "Verse View",
        "surah.pageView": "Page View",
        "surah.selectScript": "Select Script",
        "surah.plain": "Plain Text",
        "surah.view_file": "Tajweed",
        "surah.tajweed": "Tajweed",
        "surah.verse": "Verse",
        "surah.loading": "Loading...",
        "surah.shareTitle": "Share Verse",
        "surah.cancel": "Cancel",
        "surah.shareImage": "Share Image",
        "surah.end": "End of Surah",
        "surah.juz": "Juz",
        "surah.page": "Page",
        "surah.prev": "Prev",
        "surah.next": "Next",
        "home.lastRead": "Last Read",
        "home.dailyInspiration": "Daily Inspiration",
        "home.searchPlaceholder": "Search Surah...",
        "home.all": "All",
        "home.bookmarks": "Bookmarks",
        "home.verses": "Verses",
        "tasbih.title": "Digital Tasbih",
        "tasbih.tap": "Tap",
        "tasbih.reset": "Reset",
        "tasbih.target": "Target",
        "tasbih.noTarget": "No Target",
        "tasbih.history": "Dhikr History",
        "tasbih.saveInfo": "How to Save: Every time you press Reset, the last count will be automatically saved.",
        "tasbih.noHistory": "No history yet.",
        "tasbih.clearAll": "Clear All",
        "tasbih.close": "Close",
        "tasbih.targetReached": "Target Reached!",
        "tasbih.reachedMsg": "You have reached {count} counts.",
        "tasbih.continue": "Continue",
        "prayer.title": "Prayer Times",
        "prayer.next": "Next Prayer",
        "prayer.enableLoc": "Enable Location",
        "prayer.refreshLoc": "Refresh Location",
        "prayer.locating": "Locating...",
        "prayer.unknown": "Unknown Location",
        "prayer.fajr": "Fajr",
        "prayer.sunrise": "Sunrise",
        "prayer.dhuhr": "Dhuhr",
        "prayer.asr": "Asr",
        "prayer.maghrib": "Maghrib",
        "prayer.isha": "Isha",
        "prayer.testAdzan": "Test Adzan",
        "prayer.testFajr": "Test Fajr",
        "prayer.simulation": "Simulation",
        "prayer.stop": "Stop Adzan",
        "qibla.title": "Qibla Direction",
        "qibla.findingLoc": "Finding GPS...",
        "qibla.findingCity": "Finding city name...",
        "qibla.calibrate": "Calibrate Compass",
        "qibla.calibrateInfo": "Move your phone in a figure 8 pattern to improve compass accuracy.",
        "qibla.done": "Done",
        "asmaulHusna.subtitle": "99 Beautiful Names of Allah",
        "asmaulHusna.search": "Search name...",
        "dailyPrayers.subtitle": "Collection of Daily Prayers",
        "dailyPrayers.search": "Search prayer...",
        "dailyPrayers.listen": "Listen",
        "dailyPrayers.stop": "Stop",
        "dailyPrayers.pause": "Pause",
        "dailyPrayers.resume": "Resume",
        "dailyPrayers.audioUnavailable": "Audio is not available for this prayer.",
        "dzikir.subtitle": "Morning & Evening Dhikr",
        "dzikir.search": "Search dhikr...",
        "doaKhatam.subtitle": "Khatam Al-Quran Prayer",
        "doaKhatam.search": "Search prayer...",
        "doaSholat.subtitle": "Complete Salah Recitations & Intentions",
        "doaSholat.search": "Search recitation or intention...",
        "doaSholat.category.bacaan": "Recitations",
        "doaSholat.category.niatWajib": "Fardhu Prayers",
        "doaSholat.category.niatSunnah": "Sunnah Prayers",
        "doaSholat.category.sholatJenazah": "Funeral Prayer",
        "profile.title": "My Profile",
        "profile.savedBookmarks": "Saved Bookmarks",
        "profile.noBookmarks": "No bookmarks yet.",
        "profile.surahs": "Surahs",
        "profile.verses": "Verses",
        "profile.signOut": "Sign Out",
        "settings.title": "Settings",
        "settings.arabicFontSize": "Arabic Font Size",
        "settings.arabicFontFamily": "Arabic Font Style",
        "settings.fontStyleAmiri": "Amiri (Uthmani)",
        "settings.fontStyleIndopak": "Indopak",
        "settings.fontStyleLateef": "Lateef (Bold)",
        "mutabah.title": "Mutaba'ah Yaumiyah",
        "mutabah.subtitle": "Daily Worship Tracker",
        "mutabah.progress": "Today's Progress",
        "mutabah.category.fardhu": "Fardhu Prayers",
        "mutabah.category.sunnah": "Sunnah Prayers",
        "mutabah.category.quran": "Al-Quran",
        "mutabah.category.others": "Others",
        "ibadah.subuh": "Fajr",
        "ibadah.dhuhur": "Dhuhr",
        "ibadah.ashar": "Asr",
        "ibadah.maghrib": "Maghrib",
        "ibadah.isya": "Isha",
        "ibadah.tahajjud": "Tahajjud",
        "ibadah.duha": "Duha",
        "ibadah.rawatib": "Rawatib",
        "ibadah.tilawah": "Tilawah",
        "ibadah.hafalan": "Memorization",
        "ibadah.dzikirPagi": "Morning Dzikir",
        "ibadah.dzikirPetang": "Evening Dzikir",
        "ibadah.sedekah": "Charity",
        "auth.welcomeBack": "Welcome Back",
        "auth.signInSubtitle": "Sign in to sync your bookmarks",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.signIn": "Sign In",
        "auth.noAccount": "Don't have an account?",
        "auth.signUp": "Sign Up",
        "auth.createAccount": "Create Account",
        "auth.joinUs": "Join us to save your progress",
        "auth.haveAccount": "Already have an account?",
        "auth.signupSuccess": "Signup successful! Check your email.",
        "common.loading": "Loading...",
        "common.error": "An error occurred",
        "search.title": "Global Search",
        "search.placeholder": "Search keywords...",
        "search.noResults": "No results found for '{query}'",
        "search.searching": "Searching...",
        "search.resultsCount": "{count} results found",
        "bookmarks.title": "Saved Bookmarks",
        "bookmarks.tags": "My Tags",
        "bookmarks.addTag": "Add Tag",
        "bookmarks.manageTags": "Manage Tags",
        "bookmarks.filterAll": "All",
        "bookmarks.tagHafalan": "Memorization",
        "bookmarks.tagFavorit": "Favorite",
        "bookmarks.tagPenting": "Important",
        "bookmarks.noTags": "No tags yet",
        "search.backToSearch": "Back to Search",
        "menu.prophetStories": "Prophet Stories",
        "prophetStories.subtitle": "Stories of 25 Prophets in the Quran",
        "prophetStories.search": "Search prophet name..."
    }
};

const dailyVersesData = [
    {
        id: 1,
        text_id: "Maka sesungguhnya bersama kesulitan ada kemudahan.",
        text_en: "For indeed, with hardship [will be] ease.",
        ref: "QS Al-Insyirah: 5"
    },
    {
        id: 2,
        text_id: "Dan Dia mendapatimu sebagai seorang yang bingung, lalu Dia memberikan petunjuk.",
        text_en: "And He found you lost and guided [you].",
        ref: "QS Ad-Duha: 7"
    },
    {
        id: 3,
        text_id: "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.",
        text_en: "Unquestionably, by the remembrance of Allah hearts are assured.",
        ref: "QS Ar-Ra'd: 28"
    },
    {
        id: 4,
        text_id: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.",
        text_en: "Allah does not charge a soul except [with that within] its capacity.",
        ref: "QS Al-Baqarah: 286"
    },
    {
        id: 5,
        text_id: "Dan bersabarlah, sesungguhnya Allah bersama orang-orang yang sabar.",
        text_en: "And be patient. Indeed, Allah is with the patient.",
        ref: "QS Al-Anfal: 46"
    }
];

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(localStorage.getItem('appLanguage') || 'id');

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const getDailyVerse = () => {
        const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
        const verse = dailyVersesData[dayOfYear % dailyVersesData.length];
        return {
            text: language === 'id' ? verse.text_id : verse.text_en,
            ref: verse.ref
        };
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, getDailyVerse }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
